---
title: "Overlap barplots (differences)"
author: "Kai Shaman"
date: "12-09-2023"
note: "Calculation and Visualisation of Unique and Shared Neurons (differences between Pre-Language vs. English OR Pre-Language vs. Greek)"
Note: Make sure you run this script twice: for the Pre-Language vs. English and Pre-Language vs. Greek conrasts (change the variable "filename_post" in line 24).
---
```{r, include=FALSE} 
# LOAD THE PACKAGES
library(dplyr)
library(ggplot2)
library(tidyr)
library(hrbrthemes)
library(Rmisc)
library(ggsignif)
```

```{r General variables, include = FALSE}
### SET GENERAL VARIABLES
directory <- getwd() # get path to directory with files (in this case, they are in the same folder as the script)

figurename_diff <- "Difference_English_1Stage" # set the condition name to be shown on the figures: "Difference_English_1Stage" or "Difference_Greek_1Stage"
plotname_diff <- "Difference English vs. Pre-Language" # set the condition name to be shown on the figures: "Difference English vs. Pre-Language" or "Difference Greek vs. Pre-Language"
filename_post <- "data_EN.csv" # set the name of the file: "data_EN.csv" or "data_GR.csv"
filename_pre <- "data_1Stage.csv" # set the name of the file

n <- 16 # set the number of network instances (overall, both valid and invalid)
rejected <- c(6,11,13) # indicate invalid networks
n_valid <- n-length(rejected) # save the number of valid networks
m <- 8 # set the number of cell assemblies (patterns) in one data file
area_size <- 625 # number of neurons in one area
ca_size <- 7500 # number of neurons in all areas
interest <- c(1:4) # the CAs that we want to compare (in this case, CA1, CA2, CA3 and CA4)
blue_cas <- c("Blue1","Blue2")
green_cas <- c("Green1","Green2")
ca_names <- c("Blue1","Blue2","Green1","Green2","Word1","Word2","Word3","Word4") # create a list of names for each pattern's cell assembly (will be used as column names)
area_list <- c("V1","TO","AT","PFL","PML","M1L","A1","AB","PB","PFI","PMI","M1I") # create list of areas
list_extra <- c("V1","TO","AT","PFL","PML","M1L")
list_peri <- c("A1","AB","PB","PFI","PMI","M1I")
list_primary <- c("V1","M1L","A1","M1I")
list_secondary <- c("TO","PML","AB","PMI")
list_central <- c("AT","PFL","PB","PFI")
list_visual <- c("V1","TO","AT")
list_motor <- c("PFL","PML","M1L")
list_auditory <- c("A1","AB","PB")
list_articulatory <- c("PFI","PMI","M1I")
```

# DATA PREPARATION (English)
```{r STAGE 1: Preparing the raw data (single file), include = FALSE}
### RUN ONLY IF YOU HAVE DATA FROM ALL NETWORKS IN ONE FILE, COMMENT OUT IF NOT
post_ca_data <- read.csv(filename_post, header=FALSE) # load the file
post_ca_data <- data.frame(t(post_ca_data)) # transpose, if necessary
post_ca_data <- post_ca_data[3:nrow(post_ca_data),] # delete the first 2 rows (the CA names)
post_ca_data <- split.default(post_ca_data, gl(ncol(post_ca_data)/m, m)) # split the dataframe into a list of dataframes
# Loop through each file, rename the columns and save in separate dataframes:
post_ca_data_list <- list() # create empty list for a loop (it will be list of separate dataframes for each network)
for(i in 1:n) {
 tmp <- post_ca_data[[i]]
 colnames(tmp) <- ca_names
 post_ca_data_list[[i]] <- tmp}
rm(tmp, post_ca_data) # remove the variables not needed anymore

### ADD AREA AND NETWORK INFO TO EACH NETWORK'S DATAFRAME
post_ca_data_list_areas <- list() # create empty list where dataframes with added info will be saved
# Loop through the dataframes, add info about areas to each, and save in the new list
for(i in 1:n) {
 tmp <- post_ca_data_list[[i]][interest]
 tmp$Network <- rep(i, times=ca_size)
 tmp$Area <- rep(area_list, each=area_size)
 tmp <- tmp %>% mutate(AreaLang = if_else(Area %in% list_extra == TRUE, "extra", "peri"))
 tmp <- tmp %>% mutate(AreaType = if_else(Area %in% list_primary == TRUE, "primary", if_else(Area %in% list_secondary == TRUE, "secondary", "central")))
 tmp <- tmp %>% mutate(System = if_else(Area %in% list_visual == TRUE, "visual", if_else(Area %in% list_motor == TRUE, "motor", if_else(Area %in% list_auditory == TRUE, "auditory", "articulatory"))))
post_ca_data_list_areas[[i]] <- tmp}

### Combining data from valid networks into one dataframe
post_ca_data_list_valid <- post_ca_data_list_areas[- rejected] # remove rejected networks from the list
post_data <- do.call("rbind", post_ca_data_list_valid) # combine dataframes from the list into one dataframe

# ADD INFO ON WHETHER A CELL IS SHARED BETWEEN CAs OF TWO SHADES OF THE SAME COLOR OR UNIQUE
for(i in interest) {post_data[,i] <- as.numeric(post_data[,i])} # To check overlap with mutate(), convert cell values to numeric
post_data_count <- post_data
# Count average number of neurons between 2 "blue" CAs and between 2 "green" CAs:
post_data_count$Blue_Mean <- rowSums(post_data[,blue_cas])/length(blue_cas)
post_data_count$Green_Mean <- rowSums(post_data[,green_cas])/length(green_cas)
# Count shared neurons:
post_data_count <- post_data_count %>% mutate(Blue_OverlapN = if_else(rowSums(post_data[,blue_cas]) == 2, "1","0"))
post_data_count <- post_data_count %>% mutate(Green_OverlapN = if_else(rowSums(post_data[,green_cas]) == 2, "1","0"))
# Count unique neurons:
post_data_count <- post_data_count %>% mutate(Unique_Blue1 = if_else(post_data[,blue_cas[1]] == 1 & rowSums(post_data[,blue_cas]) == 1, "1","0"))
post_data_count <- post_data_count %>% mutate(Unique_Blue2 = if_else(post_data[,blue_cas[2]] == 1 & rowSums(post_data[,blue_cas]) == 1, "1","0"))
post_data_count <- post_data_count %>% mutate(Unique_Green1 = if_else(post_data[,green_cas[1]] == 1 & rowSums(post_data[,green_cas]) == 1, "1","0"))
post_data_count <- post_data_count %>% mutate(Unique_Green2 = if_else(post_data[,green_cas[2]] == 1 & rowSums(post_data[,green_cas]) == 1, "1","0"))
for(i in c((ncol(post_data)+1):ncol(post_data_count))) {post_data_count[,i] <- as.numeric(post_data_count[,i])} # Convert the values of the new columns to numeric for later analysis
# Count average number of unique neurons between 2 "blue" CAs and between 2 "green" CAs:
post_data_count$Blue_UniqueN <- rowSums(post_data_count[,grep("Unique_Blue", colnames(post_data_count))])/length(blue_cas)
post_data_count$Green_UniqueN <- rowSums(post_data_count[,grep("Unique_Green", colnames(post_data_count))])/length(green_cas)
for(i in c((ncol(post_data)+1):ncol(post_data_count))) {post_data_count[,i] <- as.numeric(post_data_count[,i])} # Convert the values of the new columns to numeric for later analysis

# COMPUTE THE SUM OF ALL SHARED AND THE SUM OF ALL UNIQUE NEURONS FOR EACH AREA FOR EACH NETWORK
post_data_count$Area <- factor(post_data_count$Area, levels = unique(post_data_count$Area)) # turn Area into a factor so the order of areas stays the same
post_data_aggr <- aggregate(cbind(Blue1,Blue2,Green1,Green2,Blue_Mean,Green_Mean,Blue_OverlapN,Green_OverlapN,Unique_Blue1,Unique_Blue2,Unique_Green1,Unique_Green2,Blue_UniqueN,Green_UniqueN) ~ Network + AreaLang + AreaType + System + Area, data = post_data_count, FUN = sum)
post_data_aggr$AreaLang <- factor(post_data_aggr$AreaLang, levels = unique(post_data_aggr$AreaLang)) # turn types of areas into factors so their order stays the same (in analysis below)
post_data_aggr$AreaType <- factor(post_data_aggr$AreaType, levels = unique(post_data_aggr$AreaType))
post_data_aggr$System <- factor(post_data_aggr$System, levels = unique(post_data_aggr$System))

# PREPARE DATAFRAME ON OVERLAP ABSOLUTE NUMBERS FOR ANALYSIS
# Select relevant columns:
post_number_raw <- post_data_aggr[,c("Network","Area","AreaLang","AreaType","System","Blue_UniqueN","Blue_OverlapN","Green_UniqueN","Green_OverlapN")] 
# Reshape data into long format:
post_number <- gather(post_number_raw, Condition, AbsoluteNo, Blue_UniqueN:Green_OverlapN, factor_key=TRUE)
post_number <- post_number %>% separate(Condition,c("Color", "Neuron_Type"), sep = "_")
post_number <- post_number %>% mutate(across(everything(), ~replace(.x, is.nan(.x), 0)))
```

# DATA PREPARATION (PRE-LANGUAGE)
```{r STAGE 1: Preparing the raw data (single file), include = FALSE}
### RUN ONLY IF YOU HAVE DATA FROM ALL NETWORKS IN ONE FILE, COMMENT OUT IF NOT
pre_ca_data <- read.csv(filename_pre, header=FALSE) # load the file
pre_ca_data <- data.frame(t(pre_ca_data)) # transpose, if necessary
pre_ca_data <- pre_ca_data[3:nrow(pre_ca_data),] # delete the first 2 rows (the CA names)
pre_ca_data <- split.default(pre_ca_data, gl(ncol(pre_ca_data)/m, m)) # split the dataframe into a list of dataframes
# Loop through each file, rename the columns and save in separate dataframes:
pre_ca_data_list <- list() # create empty list for a loop (it will be list of separate dataframes for each network)
for(i in 1:n) {
 tmp <- pre_ca_data[[i]]
 colnames(tmp) <- ca_names
 pre_ca_data_list[[i]] <- tmp}
rm(tmp, pre_ca_data) # remove the variables not needed anymore

### ADD AREA AND NETWORK INFO TO EACH NETWORK'S DATAFRAME
pre_ca_data_list_areas <- list() # create empty list where dataframes with added info will be saved
# Loop through the dataframes, add info about areas to each, and save in the new list
for(i in 1:n) {
 tmp <- pre_ca_data_list[[i]][interest]
 tmp$Network <- rep(i, times=ca_size)
 tmp$Area <- rep(area_list, each=area_size)
 tmp <- tmp %>% mutate(AreaLang = if_else(Area %in% list_extra == TRUE, "extra", "peri"))
 tmp <- tmp %>% mutate(AreaType = if_else(Area %in% list_primary == TRUE, "primary", if_else(Area %in% list_secondary == TRUE, "secondary", "central")))
 tmp <- tmp %>% mutate(System = if_else(Area %in% list_visual == TRUE, "visual", if_else(Area %in% list_motor == TRUE, "motor", if_else(Area %in% list_auditory == TRUE, "auditory", "articulatory"))))
pre_ca_data_list_areas[[i]] <- tmp}

### Combining data from valid networks into one dataframe
pre_ca_data_list_valid <- pre_ca_data_list_areas[- rejected] # remove rejected networks from the list
pre_data <- do.call("rbind", pre_ca_data_list_valid) # combine dataframes from the list into one dataframe

# ADD INFO ON WHETHER A CELL IS SHARED BETWEEN CAs OF TWO SHADES OF THE SAME COLOR OR UNIQUE
for(i in interest) {pre_data[,i] <- as.numeric(pre_data[,i])} # To check overlap with mutate(), convert cell values to numeric
pre_data_count <- pre_data
# Count average number of neurons between 2 "blue" CAs and between 2 "green" CAs:
pre_data_count$Blue_Mean <- rowSums(pre_data[,blue_cas])/length(blue_cas)
pre_data_count$Green_Mean <- rowSums(pre_data[,green_cas])/length(green_cas)
# Count shared neurons:
pre_data_count <- pre_data_count %>% mutate(Blue_OverlapN = if_else(rowSums(pre_data[,blue_cas]) == 2, "1","0"))
pre_data_count <- pre_data_count %>% mutate(Green_OverlapN = if_else(rowSums(pre_data[,green_cas]) == 2, "1","0"))
# Count unique neurons:
pre_data_count <- pre_data_count %>% mutate(Unique_Blue1 = if_else(pre_data[,blue_cas[1]] == 1 & rowSums(pre_data[,blue_cas]) == 1, "1","0"))
pre_data_count <- pre_data_count %>% mutate(Unique_Blue2 = if_else(pre_data[,blue_cas[2]] == 1 & rowSums(pre_data[,blue_cas]) == 1, "1","0"))
pre_data_count <- pre_data_count %>% mutate(Unique_Green1 = if_else(pre_data[,green_cas[1]] == 1 & rowSums(pre_data[,green_cas]) == 1, "1","0"))
pre_data_count <- pre_data_count %>% mutate(Unique_Green2 = if_else(pre_data[,green_cas[2]] == 1 & rowSums(pre_data[,green_cas]) == 1, "1","0"))
for(i in c((ncol(pre_data)+1):ncol(pre_data_count))) {pre_data_count[,i] <- as.numeric(pre_data_count[,i])} # Convert the values of the new columns to numeric for later analysis
# Count average number of unique neurons between 2 "blue" CAs and between 2 "green" CAs:
pre_data_count$Blue_UniqueN <- rowSums(pre_data_count[,grep("Unique_Blue", colnames(pre_data_count))])/length(blue_cas)
pre_data_count$Green_UniqueN <- rowSums(pre_data_count[,grep("Unique_Green", colnames(pre_data_count))])/length(green_cas)
for(i in c((ncol(pre_data)+1):ncol(pre_data_count))) {pre_data_count[,i] <- as.numeric(pre_data_count[,i])} # Convert the values of the new columns to numeric for later analysis

# COMPUTE THE SUM OF ALL SHARED AND THE SUM OF ALL UNIQUE NEURONS FOR EACH AREA FOR EACH NETWORK
pre_data_count$Area <- factor(pre_data_count$Area, levels = unique(pre_data_count$Area)) # turn Area into a factor so the order of areas stays the same
pre_data_aggr <- aggregate(cbind(Blue1,Blue2,Green1,Green2,Blue_Mean,Green_Mean,Blue_OverlapN,Green_OverlapN,Unique_Blue1,Unique_Blue2,Unique_Green1,Unique_Green2,Blue_UniqueN,Green_UniqueN) ~ Network + AreaLang + AreaType + System + Area, data = pre_data_count, FUN = sum)
pre_data_aggr$AreaLang <- factor(pre_data_aggr$AreaLang, levels = unique(pre_data_aggr$AreaLang)) # turn types of areas into factors so their order stays the same (in analysis below)
pre_data_aggr$AreaType <- factor(pre_data_aggr$AreaType, levels = unique(pre_data_aggr$AreaType))
pre_data_aggr$System <- factor(pre_data_aggr$System, levels = unique(pre_data_aggr$System))

# PREPARE pre_dataFRAME ON OVERLAP ABSOLUTE NUMBERS FOR ANALYSIS
# Select relevant columns:
pre_number_raw <- pre_data_aggr[,c("Network","Area","AreaLang","AreaType","System","Blue_UniqueN","Blue_OverlapN","Green_UniqueN","Green_OverlapN")] 
# Reshape pre_data into long format:
pre_number <- gather(pre_number_raw, Condition, AbsoluteNo, Blue_UniqueN:Green_OverlapN, factor_key=TRUE)
pre_number <- pre_number %>% separate(Condition,c("Color", "Neuron_Type"), sep = "_")
pre_number <- pre_number %>% mutate(across(everything(), ~replace(.x, is.nan(.x), 0)))
```

# COMPUTING THE DIFFERENCE
```{r}
post_number$Pre_Language <- pre_number$AbsoluteNo
post_number$Difference <- post_number$AbsoluteNo-post_number$Pre_Language
```

# Number of shared & unique neurons (ALL AREAS)
```{r, echo=FALSE}
number_all_raw <- post_number[!names(post_number) %in% c("Area", "AreaLang", "AreaType", "System", "AbsoluteNo", "Pre_Languge")]
number_all <- number_all_raw %>% group_by(Network, Color, Neuron_Type) %>% summarise_all(sum)
number_all_mean <- summarySE(number_all, measurevar="Difference", groupvars=c("Neuron_Type","Color"))
plot_number_all <- ggplot(number_all_mean, aes(fill=Color, y=Difference, x=Neuron_Type)) +
    geom_bar(position="dodge", stat="identity") +
    geom_errorbar( aes(x=Neuron_Type, ymin=Difference-se, ymax=Difference+se), width=0.2, colour="black", alpha=0.9, linewidth=0.5, position=position_dodge(0.9)) +
    ggtitle(paste0(plotname_diff, " (All areas)")) +
    scale_fill_manual(values = c("blue","darkgreen")) +
    theme(legend.position="none", plot.title = element_text(size = 22, hjust = 0.5), axis.title=element_text(size=35), axis.text.y=element_text(size=30, color ="black"), axis.text.x=element_text(size=20, color ="black"), strip.text.x = element_text(size = 25)) +
    scale_x_discrete(labels=c("OverlapN" = "Shared", "UniqueN" = "Unique")) +
    ylim(-3,70) +
    xlab("") + ylab("Number of neurons")
ggsave(plot_number_all, file=file.path('Barplots',paste0(figurename_diff, "_All.png")))
plot_number_all
```

# Number of shared & unique neurons (HUB AREAS)
```{r, echo=FALSE}
number_hub_raw <- filter(post_number, Area %in% c("AT","PFL","PB", "PFi"))
number_hub_raw <- number_hub_raw[!names(number_hub_raw) %in% c("Area", "AreaLang", "AreaType", "System", "AbsoluteNo", "Pre_Languge")]
number_hub <- number_hub_raw %>% group_by(Network, Color, Neuron_Type) %>% summarise_all(sum)
number_hub_mean <- summarySE(number_hub, measurevar="Difference", groupvars=c("Neuron_Type","Color"))
plot_number_hub <- ggplot(number_hub_mean, aes(fill=Color, y=Difference, x=Neuron_Type)) +
    geom_bar(position="dodge", stat="identity") +
    geom_errorbar( aes(x=Neuron_Type, ymin=Difference-se, ymax=Difference+se), width=0.2, colour="black", alpha=0.9, linewidth=0.5, position=position_dodge(0.9)) +
    ggtitle(paste0(plotname_diff, " (Hub areas)")) +
    scale_fill_manual(values = c("blue","darkgreen")) +
    theme(legend.position="none", plot.title = element_text(size = 21, hjust = 0.5), axis.title=element_text(size=35), axis.text.y=element_text(size=30, color ="black"), axis.text.x=element_text(size=20, color ="black"), strip.text.x = element_text(size = 25)) +
    scale_x_discrete(labels=c("OverlapN" = "Shared", "UniqueN" = "Unique")) +
    ylim(-3,25) +
    xlab("") + ylab("Number of neurons")
ggsave(plot_number_hub, file=file.path('Barplots',paste0(figurename_diff, "_Hub.png")))
plot_number_hub
```

# Number of shared & unique neurons (visual system)
```{r, echo=FALSE}
number_system_raw <- post_number[!names(post_number) %in% c("Area", "AreaLang", "AreaType", "AbsoluteNo", "Pre_Languge")]
number_system <- number_system_raw %>% group_by(Network, Color, Neuron_Type, System) %>% summarise_all(sum)
number_system_mean <- summarySE(number_system, measurevar="Difference", groupvars=c("Color", "Neuron_Type","System"),na.rm = TRUE)
plot_number_system <- ggplot(number_system_mean, aes(fill=Color, y=Difference, x=Neuron_Type)) + 
    geom_bar(position="dodge", stat="identity") +
    geom_errorbar( aes(x=Neuron_Type, ymin=Difference-se, ymax=Difference+se), width=0.2, colour="black", alpha=0.9, linewidth=0.5, position=position_dodge(0.9)) +
    ggtitle(paste0(plotname_diff)) +
    facet_wrap(~System) +
    scale_fill_manual(values = c("blue","darkgreen")) +
    theme(legend.position="right") +
    ylim(-4,25) +
    xlab("")
ggsave(plot_number_system, file=file.path('Barplots',paste0(figurename_diff, "_System.png")))
plot_number_system
```

# Number of shared & unique neurons (individual areas)
```{r, echo=FALSE}
number_mean_raw <- post_number[!names(post_number) %in% c("AreaLang", "AreaType", "AbsoluteNo", "Pre_Languge")]
number_mean <- summarySE(number_mean_raw, measurevar="Difference", groupvars=c("Area", "Neuron_Type","Color"))
plot_number_12 <- ggplot(number_mean, aes(fill=Color, y=Difference, x=Neuron_Type)) + 
    geom_bar(position="dodge", stat="identity") +
    geom_errorbar( aes(x=Neuron_Type, ymin=Difference-se, ymax=Difference+se), width=0.2, colour="black", alpha=0.9, linewidth=0.5, position=position_dodge(0.9)) +
    ggtitle(paste0(plotname_diff)) +
    facet_wrap(~Area, ncol=6, nrow=2) +
    scale_fill_manual(values = c("blue","darkgreen")) +
    theme(legend.position="none", plot.title = element_text(size = 25, hjust = 0.5), axis.title=element_text(size=35), axis.text.y=element_text(size=30, color ="black"), axis.text.x=element_text(size=20, color ="black", angle = 90), strip.text.x = element_text(size = 25)) +
    scale_x_discrete(labels=c("OverlapN" = "Shared", "UniqueN" = "Unique")) +
    ylim(-3,10) +
    xlab("") + ylab("")
ggsave(plot_number_12, file=file.path('Barplots',paste0(figurename_diff, "_Individual.png")))
plot_number_12
```

